spring.application.name=sticker.io-backend
spring.datasource.url=jdbc:postgresql://localhost:5433/sticker
spring.datasource.username=postgres
spring.datasource.password=sanjay
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.platform=postgres
logging.level.org.springframework=DEBUG
jwt.secret=0e0c499140ac3b198c1ec6d1d6c1b43d2741e52178477e396a37ad052813db83408f744f9bed4fefc88d6014b3d114b60863a4e5c6711540c1a5226ac7b9a68c
jwt.expiration=17200000

